#define JADE_PLATFORM
#define PEARL_PLATFORM_B0
#define PEARL_PLATFORM_C0
#define PEARL_FPGA_PLATFORM 0
#define JADE_FPGA_PLATFORM 0
#define PLATFORM_WMAC_MODE ap
#define PLATFORM_DEFAULT_BOARD_ID 1240
#define PLATFORM_ARC7_MMU_VER 3
#define FLASH_SUPPORT_256KB
#define UNIFIED_IMAGE 0
