#include "base/qtn_base_current_platform.h"
#define JADE_PLATFORM
#define PEARL_PLATFORM
#define IMAGE_DSP_TEST 0
#define DDT_ENABLE 0
#define PEARL_PLATFORM_MISALIGN_WAR
#define CORE_VOLTAGE_EXTERNAL
#define TOPAZ_FPGA_PLATFORM 0
#define PEARL_ASIC_REV_A0
#define PEARL_MULTI_AUC
#define AUC_TOTAL_CORES_NUM 6
#define AUC_CORES_NUM 3
#define AUC_HW_CORES_NUM AUC_CORES_NUM
#define PEARL_TQEW_DESC_LINK_MODE
#define TOPAZ_RFIC6_PLATFORM
#define ENABLE_C0_CALIB
#define ENABLE_C0
#define PEARL_PLATFORM_5GAX 0
#define PEARL_PLATFORM_10GAX 1
#define WPA_TKIP_SUPPORT 1
#define SIGMA_TESTBED_SUPPORT 0
